### ISSUE TITLE
noise_change interface

### ISSUE THREAD

**Issue by mrmaximuzz** [AleNriG/SIMS#4]
Как мне показалось, интерфейс вызова программы можно улучшить.

-  Входной файл ожидается в формате .csv, имя для выходного файла создается автоматически и этому имени задается расширение .csv, но выходной файл не является корректным csv-файлом - данные в нем используют простой формат записи через пробел. Несогласованность форматов может породить ошибки при дальнейшем использовании результатов вычислений.
-  Откуда берется исходный файл? Его шапка довольно странная, например в `test.csv`:
        `A,A1`
        `,12C2`
Формат довольно странный, причем эти две строки все равно вырезаются в скрипте запуска `start.sh (21): sed -e '1,2d' ${1} > ${data_formatted}` . Вообще можно это все сделать в самой программе, а не во внешнем скрипте - питон все же гораздо более кроссплатформенный, чем баш, и тогда полученная программа легко запустится и на винде, и на mac os.

**Comment by AleNriG** [comment]
1. да, выходной .csv фал на разделители я не проверил.
2. исходный файл берётся из анализатора спектрометра. он всегда выдаёт првую строку пронумерованную как А А1 и т.д., где А - столбец вреиени для ионов из столбца А1 и т.д., а 12С и др. -- сами названия ионов. Вырезаю из шапки, я их вырезаю из шапки, т.к. для проги по обработке данных они мне не нужны. и да, то что вырезать в самом питоне, чтобы отелаться от привязки к шеллу я уже подумываю.
